/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBDisplay.h"

@class NSMutableDictionary, SBAlertWindow, SBAlertDisplay;

@interface SBAlert : SBDisplay {
	SBAlertDisplay* _display;
	NSMutableDictionary* _dictionary;
	SBAlertWindow* _deferredAlertWindow;
}
+(void)registerForAlerts;
+(id)alertWindow;
+(void)test;
-(void)dealloc;
-(id)display;
-(void)setDisplay:(id)display;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)setObject:(id)object forKey:(id)key;
-(id)objectForKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(BOOL)undimsDisplay;
-(float)finalAlpha;
-(CGRect)alertWindowRect;
-(Class)alertWindowClass;
-(void)_updateStatusBarLockAndTime;
-(int)statusBarStyleOverridesToCancel;
-(void)activate;
-(void)tearDownAlertWindow:(id)window;
-(void)removeFromView;
-(void)deactivate;
-(int)effectiveStatusBarStyle;
-(double)autoDimTime;
-(int)statusBarStyle;
-(void)didAnimateLockKeypadIn;
-(void)didAnimateLockKeypadOut;
-(void)didFinishAnimatingIn;
-(void)didFinishAnimatingOut;
-(BOOL)handleMenuButtonTap;
@end

