/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"
#import <UIKit/UIView.h>

@class SBAlert;

@interface SBAlertDisplay : UIView {
	SBAlert* _alert;
	unsigned _displaysAboveStatusBar : 1;
	unsigned _shouldAnimateIn : 1;
}
-(id)initWithFrame:(CGRect)frame;
-(void)setAlert:(id)alert;
-(id)alert;
-(void)launchURL:(id)url;
-(void)dismiss;
-(void)setHandlerAlreadyActive:(BOOL)active;
-(void)alertDisplayWillBecomeVisible;
-(void)alertDisplayBecameVisible;
-(BOOL)displaysAboveStatusBar;
-(void)setDisplaysAboveStatusBar:(BOOL)bar;
-(BOOL)isReadyToBeRemovedFromView;
-(void)setShouldAnimateIn:(BOOL)animateIn;
-(BOOL)shouldAnimateIn;
-(void)alertWindowResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAddClippingViewDuringRotation;
@end

@interface SBAlertDisplay (PhoneNumberResolution)
+(id)imageForPerson:(void*)person display:(id)display isFullscreen:(BOOL*)fullscreen;
@end

@interface SBAlertDisplay (SIMToolkitExtensions)
+(id)alertBackgroundColor;
@end

