/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class CPDistributedNotificationCenter, NSTimer, NSMutableArray;

@interface SBAlertItemsController : NSObject {
	NSMutableArray* _lockedAlertItems;
	NSMutableArray* _unlockedAlertItems;
	NSTimer* _autoDismissTimer;
	CPDistributedNotificationCenter* _notificationCenter;
	unsigned _notificationClientCount;
	BOOL _systemShuttingDown;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)convertAnimatingUnlockedAlertsToLockedAlerts;
-(void)deactivateAllAlertItems;
-(void)resetAutoDismissTimer;
-(void)activateAlertItem:(id)item;
-(void)deactivateAlertItem:(id)item reason:(int)reason;
-(void)deactivateAlertItem:(id)item;
-(void)deactivateAlertItemsOfClass:(Class)aClass;
-(void)deactivateAlertItemsOfClass:(Class)aClass reason:(int)reason;
-(void)deactivateVisibleAlertItemOfClass:(Class)aClass reason:(int)reason;
-(void)autoDismissAlertItem:(id)item;
-(id)alertItemOfClass:(Class)aClass;
-(id)alertItemsOfClass:(Class)aClass;
-(BOOL)isShowingAlertOfClass:(Class)aClass;
-(BOOL)isShowingAlert:(id)alert;
-(BOOL)isShowingAlerts;
-(id)visibleAlertItem;
-(BOOL)deactivateAlertForMenuClick;
-(id)deactivateAlertItemsForLock;
-(BOOL)dontLockOverAlertItems;
-(void)deactivateAlertItemsForAlertActivation;
-(void)noteVolumeOrLockPressedOverLockedAlerts;
-(void)notifySystemOfAlertItemActivation:(id)alertItemActivation;
-(void)noteSystemShuttingDown;
-(void)_notificationClientStarted:(id)started;
-(void)_notificationClientEnded:(id)ended;
@end

