/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UITextFieldDelegate.h"
#import "SBSlidingAlertDisplay.h"

@class UIScrollView, SBTextDisplayView, UIKeyboard, UINavigationBar, UITextField;

@interface SBAlertInputView : SBSlidingAlertDisplay <UITextFieldDelegate> {
	UITextField* _inputTextField;
	UIKeyboard* _keyboard;
	SBTextDisplayView* _textDisplay;
	UIScrollView* _scroller;
	UINavigationBar* _bar;
	BOOL _digitsOnly;
	id _delegate;
	int _minLength;
	int _maxLength;
}
+(id)newTopBarForInstance:(id)instance;
+(id)newBottomBarForInstance:(id)instance;
-(void)setDelegate:(id)delegate;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(BOOL)showsDesktopImage;
-(void)setMiddleContentAlpha:(float)alpha;
-(void)setText:(id)text;
-(void)alertDisplayWillBecomeVisible;
-(void)setMinLength:(int)length;
-(void)setMaxLength:(int)length;
-(void)_setNavigationBar:(id)bar;
-(void)_setInputTextField:(id)field;
-(void)_setKeyboard:(id)keyboard;
-(BOOL)textField:(id)field shouldInsertText:(id)text replacingRange:(NSRange)range;
-(void)setDigitsOnly:(BOOL)only;
-(void)sbAlertInputViewSendClicked:(id)clicked;
-(void)sbAlertInputViewCancelClicked:(id)clicked;
-(id)textField;
-(void)_sendClicked:(id)clicked;
@end

