/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAppSwitcherBarViewDelegate.h"
#import "SBIconDelegate.h"
#import <Foundation/NSObject.h>

@class SBApplicationIcon, SBAppSwitcherModel, SBAppSwitcherBarView, SBNowPlayingBar;

@interface SBAppSwitcherController : NSObject <SBIconDelegate, SBAppSwitcherBarViewDelegate> {
	SBAppSwitcherModel* _model;
	SBNowPlayingBar* _nowPlaying;
	SBAppSwitcherBarView* _bottomBar;
	SBApplicationIcon* _pushedIcon;
	BOOL _editing;
}
@property(readonly, assign, nonatomic) SBAppSwitcherModel* model;
+(id)sharedInstance;
+(id)sharedInstanceIfAvailable;
-(id)init;
-(void)dealloc;
-(void)applicationLaunched:(id)launched;
-(void)applicationDied:(id)died;
-(void)applicationSuspended:(id)suspended;
-(void)applicationsRemoved:(id)removed andAdded:(id)added;
-(void)viewWillAppear;
-(void)viewDidDisappear;
-(void)downloadsChanged:(id)changed withRemovals:(id)removals;
-(void)downloadItemUpdatingStatusChanged:(id)changed;
-(id)switcherViewForApp:(id)app orientation:(int)orientation;
-(BOOL)handleMenuButtonTap;
-(BOOL)nowPlayingControlsVisible;
-(id)applicationIconForDisplayIdentifier:(id)displayIdentifier;
-(id)_applicationIconsExcept:(id)except forOrientation:(int)orientation;
-(BOOL)_inEditMode;
-(void)_beginEditing;
-(void)_stopEditing;
-(void)_removeApplicationFromRecents:(id)recents;
-(id)_currentDownloads;
-(id)_currentIcons;
-(id)_iconForApplication:(id)application;
-(id)_iconForDownload:(id)download;
-(void)iconTapped:(id)tapped;
-(BOOL)iconShouldAllowTap:(id)icon;
-(void)iconHandleLongPress:(id)press;
-(void)iconTouchBegan:(id)began;
-(float)iconScale:(id)scale;
-(int)closeBoxTypeForIcon:(id)icon;
-(void)iconCloseBoxTapped:(id)tapped;
-(void)appSwitcherBarRemovedFromSuperview:(id)superview;
-(BOOL)appSwitcherBar:(id)bar scrollShouldCancelInContentForView:(id)scroll;
@end

