/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class MPAudioDeviceController, UIButton, UISlider, UILabel;

@interface SBAwayMediaControlsView : UIView {
	unsigned _beganSeeking : 1;
	int _seekingDirection;
	UIButton* _prevButton;
	UIButton* _nextButton;
	UIButton* _playPauseButton;
	UISlider* _slider;
	UIButton* _routeButton;
	UILabel* _routeLabel;
	MPAudioDeviceController* _audioDeviceController;
	int _orientation;
}
@property(assign, nonatomic) int orientation;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setAlpha:(float)alpha;
-(void)removeFromSuperview;
-(void)_playPauseButtonAction:(id)action;
-(void)_changeTrackButtonDown:(id)down;
-(void)_changeTrackButtonUp:(id)up;
-(void)_changeTrackButtonEndSeek:(id)seek;
-(void)_changeTrackButtonTouchPause:(id)pause;
-(void)_volumeChange:(id)change;
-(void)_showAudioRoutes:(id)routes;
-(void)_registerForNowPlayingNotifications;
-(void)_unregisterForNowPlayingNotifications;
-(void)_registerForVolumeNotifications;
-(void)_unregisterForVolumeNotifications;
-(void)_nowPlayingChanged:(id)changed;
-(void)_systemVolumeChanged:(id)changed;
-(void)audioDeviceControllerAudioRoutesChanged:(id)changed;
-(void)audioDeviceControllerMediaServerDied:(id)died;
-(id)_newButtonWithImage:(id)image action:(SEL)action tag:(int)tag;
-(void)_showRouteButton:(BOOL)button volumeSlider:(BOOL)slider animated:(BOOL)animated;
-(CGRect)_sliderFrameWithRouteButton:(BOOL)routeButton;
-(void)_updateInformation;
@end

