/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface SBBluetoothController : NSObject {
	NSMutableArray* _devices;
}
+(id)sharedInstance;
-(void)dealloc;
-(id)firstBTDeviceToReportBatteryLevel;
-(BOOL)canReportBatteryLevel;
-(int)batteryLevel;
-(void)noteDevicesChanged;
-(void)startWatchingForDevices;
-(void)stopWatchingForDevices;
-(void)iapDeviceChanged:(id)changed;
-(void)addDeviceNotification:(id)notification;
-(void)removeDeviceNotification:(id)notification;
-(void)connectionChanged:(id)changed;
-(void)batteryChanged:(id)changed;
-(void)updateBattery;
-(id)deviceForAudioRoute:(id)audioRoute;
@end

