/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"

@class UIWebClip;

@interface SBBookmarkIcon : SBLeafIcon {
	UIWebClip* _webClip;
}
-(id)initWithWebClip:(id)webClip;
-(void)dealloc;
-(BOOL)allowsUninstall;
-(id)generateIconImage:(int)image;
-(id)displayName;
-(id)leafIdentifier;
-(void)launch;
-(void)completeUninstall;
-(id)webClip;
-(id)folderTitleOptions;
-(id)folderFallbackTitle;
@end

