/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>


@interface SBCalendarController : NSObject {
	CFDateFormatterRef _dayFormatter;
	CFDateFormatterRef _timeFormatter;
	int _unreadInvitationCount;
	CalEventExpirationMonitor* _expirationMonitor;
	CalAlarmEngine* _alarmEngine;
	CalDatabase* _database;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)_finishInitialization;
-(void)_databaseChanged:(id)changed;
-(void)_unreadInvitationsExpired:(id)expired;
-(void)_setInvitationUnreadCount:(int)count;
-(int)unreadInvitationCount;
-(void)_alertForInvitations;
-(void)_adjustOnWake;
-(void)_didWakeFromSleep;
-(void)_alarmsDidFire:(id)_alarms;
-(void)_checkForTimeZoneIfNecessary;
-(void)_significantTimeChange;
-(id)_stringForDay:(XXStruct_fhKmAA)day withLongFormatString:(id)longFormatString useAbbreviatedFormats:(BOOL)formats;
-(id)stringForDay:(XXStruct_fhKmAA)day withLongFormatString:(id)longFormatString;
-(id)abbreviatedStringForDay:(XXStruct_fhKmAA)day withLongFormatString:(id)longFormatString;
-(CFDateFormatterRef)timeFormatter;
-(id)_dayStringForDate:(double)date allDay:(BOOL)day shortFormat:(BOOL)format;
-(id)_timeStringForDate:(double)date;
-(id)timeStringForDate:(double)date inTimeZone:(id)timeZone;
-(id)dateStringForDate:(double)date allDay:(BOOL)day shortFormat:(BOOL)format;
-(void)playAlertSound;
@end

