/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDeviceLockView.h"

@class SBDeviceLockKeypad;

@interface SBDeviceLockViewWithKeypad : SBDeviceLockView {
	SBDeviceLockKeypad* _keypad;
}
-(id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;
-(void)dealloc;
-(id)keypadView;
-(void)setPasscode:(id)passcode;
-(BOOL)playsKeyboardClicks;
-(void)setPlaysKeyboardClicks:(BOOL)clicks;
-(BOOL)showsEmergencyCallButton;
-(void)setShowsEmergencyCallButton:(BOOL)button;
-(void)deviceLockEntryFieldTextDidChange:(id)deviceLockEntryFieldText;
-(void)phonePad:(id)pad keyDown:(BOOL)down;
-(void)phonePad:(id)pad keyUp:(BOOL)up;
@end

