/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDeviceLockViewWithKeyboard.h"


@interface SBDeviceLockViewWithKeyboardWildcat : SBDeviceLockViewWithKeyboard {
}
-(void)_centerStatusView;
-(void)_layoutForCurrentOrientation;
-(id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;
-(void)setMinimized:(BOOL)minimized;
-(void)setInterfaceOrientation:(int)orientation;
-(void)returnKeyPressed:(id)pressed;
-(void)hardwareReturnKeyPressed:(id)pressed;
@end

