/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBDeviceLockKeypad.h"

@class UIView;

@interface SBDeviceLockKeypadWildcat : SBDeviceLockKeypad {
	UIView* _glowView;
}
+(id)keypadImage;
+(id)pressedImage;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setHighlighted:(BOOL)highlighted;
-(float)_yFudge;
-(CGRect)_rectForKey:(int)key;
-(BOOL)deleteKeyChar;
-(BOOL)cancelKeyChar;
@end

