/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDeviceLockViewWithKeyboard.h"


@interface SBDeviceLockViewWithKeyboardPhone : SBDeviceLockViewWithKeyboard {
}
-(id)_initWithStyle:(int)style interfaceOrientation:(int)orientation showsEmergencyCall:(BOOL)call;
-(BOOL)showsEmergencyCallButton;
-(void)setShowsEmergencyCallButton:(BOOL)button;
-(void)returnKeyPressed:(id)pressed;
-(void)hardwareReturnKeyPressed:(id)pressed;
-(void)_layoutForCurrentOrientation;
@end

