/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListView.h"


@interface SBDockIconListView : SBIconListView {
}
+(int)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(int)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
+(BOOL)shouldShowNewDock;
+(id)backgroundImageForOrientation:(int)orientation;
-(id)initForOrientation:(int)orientation;
-(id)initWithFrame:(CGRect)frame;
-(void)_updateForOrientationAnimationStopped;
-(void)_updateForOrientation:(int)orientation duration:(double)duration;
-(void)setOrientation:(int)orientation;
-(void)setOrientation:(int)orientation duration:(double)duration;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(int)visibleIconsInDock;
-(int)iconsInRowForSpacingCalculation;
-(float)topIconInset;
-(int)rowAtPoint:(CGPoint)point;
-(float)_additionalSideInsetToCenterIcons;
-(CGPoint)originForIconAtX:(unsigned)x Y:(unsigned)y;
-(int)columnAtPoint:(CGPoint)point;
@end

