/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImageView.h>


@interface SBDownloadingProgressBar : UIImageView {
	UIImageView* _clipView;
	UIImageView* _fillView;
	float _progress;
}
+(float)defaultHeight;
+(CGRect)defaultFrameForIconBounds:(CGRect)iconBounds;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)trackImage;
-(id)fillImage;
-(void)setProgress:(float)progress;
-(float)progress;
-(void)updateFill;
@end

