/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"

@class SSDownload, SSDownloadStatus, NSString, SBDownloadingProgressBar;

@interface SBDownloadingIcon : SBLeafIcon {
	NSString* _leafIdentifier;
	NSString* _applicationBundleID;
	SSDownload* _download;
	SBDownloadingProgressBar* _progressView;
	float _progress;
	BOOL _installing;
	BOOL _wasUninstalledByUser;
	SSDownloadStatus* _lastStatus;
}
+(id)leafIdentifierForDownloadUniqueID:(id)downloadUniqueID;
+(id)leafIdentifierForDownload:(id)download;
-(id)initWithLeafIdentifier:(id)leafIdentifier;
-(id)initWithDownload:(id)download;
-(void)dealloc;
-(id)description;
-(void)setLeafIdentifier:(id)identifier;
-(id)identifierForCorrespondingApplicationIcon;
-(id)generateIconImage:(int)image;
-(void)setDisplayedIconImage:(id)image;
-(void)updateDisplayName;
-(BOOL)shouldEllipsizeLabel;
-(id)displayName;
-(id)leafIdentifier;
-(void)launch;
-(BOOL)allowsUninstall;
-(void)setGhostly:(BOOL)ghostly requester:(int)requester;
-(void)closeBoxTapped;
-(void)completeUninstall;
-(void)reloadForStatusChange;
-(float)progress;
-(id)applicationBundleID;
-(void)setApplicationBundleID:(id)anId;
-(void)setDownload:(id)download;
-(id)download;
-(void)retry;
-(void)remove;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
-(void)_showAlertForError:(id)error;
-(void)_thumbnailAvailableNotification:(id)notification;
@end

