/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UITextFieldDelegate.h"
#import <UIKit/UIView.h>

@class SBFolderTitleLabel, SBFolderTextField, SBFolderIconListView, SBFolder, UIImageView;

@interface SBFolderView : UIView <UITextFieldDelegate> {
	SBFolder* _folder;
	SBFolderTitleLabel* _label;
	SBFolderTextField* _textField;
	SBFolderIconListView* _iconListView;
	BOOL _isEditing;
	UIImageView* _shadows[10];
	unsigned _rows;
	XXStruct_9ihRqB _notchInfo;
	int _orientation;
}
+(CGSize)boundsSizeForRows:(unsigned)rows orientation:(int)orientation;
+(CGRect)linenRectForRows:(unsigned)rows orientation:(int)orientation;
+(CGRect)linenNotchRectForRows:(unsigned)rows orientation:(int)orientation notchInfo:(XXStruct_9ihRqB)info;
-(id)initWithRows:(unsigned)rows notchInfo:(XXStruct_9ihRqB)info orientation:(int)orientation;
-(unsigned)rows;
-(CGRect)rectForNotchLinen;
-(void)setIconListView:(id)view;
-(id)iconListView;
-(void)dealloc;
-(void)setFolder:(id)folder;
-(void)setFolderName:(id)name;
-(void)setIsEditing:(BOOL)editing animated:(BOOL)animated;
-(void)enableShiftForFolderTextFieldAfterBeginEditing;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldClear:(id)textField;
-(NSRange)textField:(id)field willChangeSelectionFromCharacterRange:(NSRange)characterRange toCharacterRange:(NSRange)characterRange3;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)setBackgroundAlpha:(float)alpha;
-(id)editTitleField;
-(id)_shadowForPosition:(int)position;
-(void)_placeShadow:(int)shadow;
-(void)_placeShadows;
@end

