/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIcon.h"

@class NSMutableSet, SBFolder, UIImageView, SBDownloadingProgressBar;

@interface SBFolderIcon : SBIcon {
	SBFolder* _folder;
	UIImageView* _iconBorderView;
	UIImageView* _scrollingIconImageView;
	int _iconScrollPosition;
	SBDownloadingProgressBar* _progressBar;
	NSMutableSet* _animatingIcons;
}
-(id)initWithFolder:(id)folder;
-(void)dealloc;
-(id)generateIconImage:(int)image;
-(float)_contentsRectYForScrollPosition:(int)scrollPosition scaledHeight:(float)height;
-(int)iconScrollPosition;
-(void)setIconScrollPosition:(int)position duration:(double)duration;
-(void)setIsOverlapping:(BOOL)overlapping;
-(CGRect)rectForMiniIconAtIndex:(unsigned)index;
-(id)croppedImageForIcon:(id)icon;
-(id)imageForReflection;
-(void)setDisplayedIconImage:(id)image;
-(CGAffineTransform)transformToMakeIconBorderExpandToSizeOfDropGlow;
-(void)showDropGlow:(BOOL)glow;
-(CGImageRef)createComposedIconImageUsingContext:(CGContextRef)context;
-(CGPoint)iconOverlayPosition;
-(void)placeGhostlyImageView;
-(void)setGhostly:(BOOL)ghostly requester:(int)requester;
-(id)progressBar;
-(id)iconBorderView;
-(id)snapshotOfSubview:(id)subview positionedForSuperview:(id)superview;
-(id)displayName;
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
-(id)folder;
-(id)description;
-(void)launch;
-(BOOL)allowsTapWhileEditing;
-(BOOL)delaysUnhighlightWhenTapped;
-(double)grabDurationForEvent:(id)event;
-(void)_updateBadgeValue;
-(void)_updateProgressBar;
-(void)noteContainedIconsAdded:(id)added removed:(id)removed;
-(void)noteContainedIconBadgeChanged:(id)changed;
-(void)noteContainedIconImageChanged:(id)changed;
-(void)noteContainedIconDownloadingStateChanged:(id)changed;
-(void)noteIcon:(id)icon isAnimatingIn:(BOOL)anIn;
-(CGSize)_sizeOfMiniIconGridOfType:(int)type;
-(id)_miniIconGridOfType:(int)type;
-(id)miniImageForIcon:(id)icon;
-(CGRect)_rectForMiniIconAtIndex:(unsigned)index forGridType:(int)gridType;
-(void)_scrollAnimationDidStop:(id)_scrollAnimation finished:(id)finished context:(void*)context;
-(void)_delegateCloseFolderAnimated:(BOOL)animated;
-(void)_delegateOpenFolder:(id)folder animated:(BOOL)animated;
@end

