/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"
#import "SBIcon.h"

@class SBIconLabel, SBIconBadge, NSTimer, SBIconImageContainerView, UIImageView, UIImage, SBIconImageView;
@protocol SBIconDelegate;

@interface SBIcon : UIView {
	id<SBIconDelegate> _delegate;
	SBIconImageContainerView* _iconImageContainer;
	SBIconImageView* _iconImageView;
	UIImageView* _iconDarkeningOverlay;
	UIImageView* _ghostlyImageView;
	UIImageView* _reflection;
	UIImageView* _shadow;
	SBIconBadge* _badge;
	id _badgeNumberOrString;
	SBIconLabel* _label;
	UIView* _closeBox;
	UIImageView* _dropGlow;
	unsigned _isShowingImages : 1;
	unsigned _drawsLabel : 1;
	unsigned _isHidden : 1;
	unsigned _isRevealable : 1;
	unsigned _inDock : 1;
	unsigned _inSwitcher : 1;
	unsigned _isGrabbed : 1;
	unsigned _isOverlapping : 1;
	unsigned _refusesRecipientStatus : 1;
	unsigned _highlighted : 1;
	unsigned _isJittering : 1;
	unsigned _allowJitter : 1;
	unsigned _touchDownInIcon : 1;
	NSTimer* _delayedUnhighlightTimer;
	unsigned _onWallpaper : 1;
	unsigned _ghostlyRequesters;
	unsigned _uninstalled : 1;
	float _iconImageAlpha;
	float _iconImageBrightness;
	float _iconLabelAlpha;
	float _accessoryAlpha;
	CGPoint _unjitterPoint;
	CGPoint _grabPoint;
	NSTimer* _longPressTimer;
	UIImage* _cachedIconImages[7];
}
@property(assign, nonatomic) id<SBIconDelegate> delegate;
+(CGSize)defaultIconSize;
+(CGSize)defaultIconImageSize;
+(id)genericAppIcon:(int)icon;
+(void)enqueueReusableIconImageView:(id)view;
+(id)dequeueReusableIconImageView;
+(id)_jitterPositionAnimation;
+(id)_jitterTransformAnimation;
-(id)initWithDefaultSize;
-(void)dealloc;
-(id)representation;
-(BOOL)matchesRepresentation:(id)representation;
-(void)localeChanged;
-(float)iconScale;
-(void)showIconAnimationDidStop:(id)showIconAnimation didFinish:(id)finish icon:(id)icon;
-(void)setIsHidden:(BOOL)hidden animate:(BOOL)animate;
-(BOOL)isHidden;
-(void)setIsRevealable:(BOOL)revealable;
-(BOOL)isRevealable;
-(id)displayName;
-(int)localizedCompareDisplayNames:(id)names;
-(BOOL)matchesEntity:(id)entity;
-(id)tags;
-(BOOL)launchEnabled;
-(void)setDisplayedIconImage:(id)image;
-(id)generateIconImage:(int)image;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(id)getIconImage:(int)image;
-(void)purgeCachedImages;
-(void)reloadIconImage;
-(id)imageForReflection;
-(id)reflectedIcon:(BOOL)icon;
-(void)setIconImageAlpha:(float)alpha;
-(void)setIconLabelAlpha:(float)alpha;
-(BOOL)isShowingImages;
-(void)setShowsImages:(BOOL)images;
-(id)iconImageView;
-(void)prepareIconImageViewForRecycling;
-(void)updateLabelOrigin;
-(BOOL)shouldEllipsizeLabel;
-(void)updateLabel;
-(void)setDrawsLabel:(BOOL)label;
-(void)updateLabelKerningAndEllipsing;
-(int)badgeValue;
-(id)badgeNumberOrString;
-(void)setBadge:(id)badge;
-(BOOL)hasBadge;
-(id)badgeView;
-(id)_automationID;
-(BOOL)pointMostlyInside:(CGPoint)inside withEvent:(id)event;
-(id)darkenedIconImage:(id)image alpha:(float)alpha;
-(void)darkenIconImage:(float)image;
-(CGPoint)iconOverlayPosition;
-(void)_darkenIconImage:(float)image;
-(BOOL)allowsTapWhileEditing;
-(BOOL)delaysUnhighlightWhenTapped;
-(BOOL)isHighlighted;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setHighlighted:(BOOL)highlighted delayUnhighlight:(BOOL)unhighlight;
-(void)_delayedUnhighlight;
-(void)setInDock:(BOOL)dock;
-(BOOL)isInDock;
-(id)_shadowImageName;
-(void)_updateShadow;
-(void)setDisplaysOnWallpaper:(BOOL)wallpaper;
-(void)setLabelDisplaysOnWallpaper:(BOOL)wallpaper;
-(void)setDisplaysInSwitcher:(BOOL)switcher;
-(BOOL)showsReflection;
-(float)_reflectionImageOffset;
-(void)setFrame:(CGRect)frame;
-(void)setIsJittering:(BOOL)jittering;
-(void)setAllowJitter:(BOOL)jitter;
-(BOOL)allowJitter;
-(void)removeAllIconAnimations;
-(void)setIconPosition:(CGPoint)position;
-(void)setRefusesRecipientStatus:(BOOL)status;
-(BOOL)canReceiveGrabbedIcon:(id)icon;
-(double)grabDurationForEvent:(id)event;
-(void)setIsGrabbed:(BOOL)grabbed;
-(BOOL)isGrabbed;
-(void)setIsOverlapping:(BOOL)overlapping;
-(CGAffineTransform)transformToMakeDropGlowShrinkToIconSize;
-(void)prepareDropGlow;
-(void)showDropGlow:(BOOL)glow;
-(void)removeDropGlow;
-(id)dropGlow;
-(BOOL)isShowingDropGlow;
-(CGContextRef)grayscaleContext;
-(CGContextRef)alphaContext;
-(CGImageRef)createComposedIconImageUsingContext:(CGContextRef)context;
-(void)placeGhostlyImageView;
-(void)prepareGhostlyImage;
-(void)setGhostly:(BOOL)ghostly requester:(int)requester;
-(void)removeGhostlyImage;
-(BOOL)isGhostly;
-(int)ghostlyRequesters;
-(void)longPressTimerFired;
-(void)cancelLongPressTimer;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(BOOL)isTouchDownInIcon;
-(void)setTouchDownInIcon:(BOOL)icon;
-(void)launch;
-(BOOL)allowsUninstall;
-(void)hideCloseBoxAnimationDidStop:(id)hideCloseBoxAnimation didFinish:(id)finish closeBox:(id)box;
-(id)_newCloseBoxOfType:(int)type;
-(void)setShowsCloseBox:(BOOL)box;
-(BOOL)isShowingCloseBox;
-(void)closeBoxTapped;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(UIEdgeInsets)snapshotEdgeInsets;
-(void)setShadowsHidden:(BOOL)hidden;
-(void)_updateShadowFrameForShadow:(id)shadow;
-(void)_updateShadowFrame;
-(BOOL)_delegatePositionIsEditable;
-(void)_delegateTouchEnded:(BOOL)ended;
-(BOOL)_delegateTapAllowed;
-(int)_delegateCloseBoxType;
-(id)createShadowImageView;
-(void)completeUninstall;
-(void)setUninstalled;
-(BOOL)isUninstalled;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
-(id)folderTitleOptions;
-(id)folderFallbackTitle;
@end

@interface SBIcon (SBApplicationIcon)
-(BOOL)isApplicationIcon;
-(id)application;
@end

@interface SBIcon (SBBookmarkIcon)
-(BOOL)isBookmarkIcon;
@end

@interface SBIcon (SBRemovedFolderHole)
-(BOOL)isRemovedFolderHole;
@end

@interface SBIcon (SBDestinationHole)
-(BOOL)isDestinationHole;
@end

@interface SBIcon (SBNullIcon)
-(BOOL)isNullIcon;
@end

@interface SBIcon (SBDownloadingIcon)
-(BOOL)isDownloadingIcon;
-(id)download;
@end

@interface SBIcon (SBUserInstalledApplicationIcon)
-(BOOL)isUserInstalledApplicationIcon;
@end

@interface SBIcon (SBWidgetApplicationIcon)
-(BOOL)isWidgetApplicationIcon;
@end

@interface SBIcon (SBFolderIcon)
-(BOOL)isFolderIcon;
-(id)folder;
-(id)enclosingFolder;
@end

@interface SBIcon (SBLeafIcon)
-(BOOL)isLeafIcon;
-(id)leafIdentifier;
-(id)webClip;
-(id)applicationBundleID;
@end

