/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconDelegate <NSObject>
@optional
-(float)iconScale:(id)scale;
-(BOOL)iconAllowJitter:(id)jitter;
-(BOOL)iconPositionIsEditable:(id)editable;
-(void)iconHandleLongPress:(id)press;
-(void)iconTouchBegan:(id)began;
-(void)icon:(id)icon touchMovedWithEvent:(id)event;
-(void)icon:(id)icon touchEnded:(BOOL)ended;
-(BOOL)iconShouldAllowTap:(id)icon;
-(void)iconTapped:(id)tapped;
-(BOOL)icon:(id)icon canReceiveGrabbedIcon:(id)icon2;
-(void)iconDownloadStateChanged:(id)changed;
-(void)iconUninstall:(id)uninstall;
-(void)icon:(id)icon closeFolderAnimated:(BOOL)animated;
-(void)icon:(id)icon openFolder:(id)folder animated:(BOOL)animated;
-(int)closeBoxTypeForIcon:(id)icon;
-(void)iconCloseBoxTapped:(id)tapped;
@end

