/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SBRootFolder, NSSet, NSDictionary, NSMutableSet, NSMutableDictionary;

@interface SBIconModel : NSObject {
	NSDictionary* _lastKnownUserGeneratedIconState;
	NSMutableDictionary* _leafIconsByIdentifier;
	NSSet* _hiddenIconTags;
	NSSet* _visibleIconTags;
	NSMutableSet* _downloadedIconIDs;
	SBRootFolder* _rootFolder;
	BOOL _needsRelayout;
}
+(id)sharedInstance;
+(id)_modernIconCellForCell:(id)cell;
+(id)_modernIconListForList:(id)list;
+(id)_modernIconListsForLists:(id)lists;
+(id)modernIconStateForState:(id)state;
-(id)init;
-(void)dealloc;
-(id)rootFolder;
-(void)localeChanged;
-(void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;
-(BOOL)isIconVisible:(id)visible;
-(void)replaceDownloadingIconIdentifiers:(id)identifiers withAppIconIdentifiers:(id)appIconIdentifiers;
-(void)uninstallLeafIcon:(id)icon;
-(id)addDownloadingIconForDownload:(id)download;
-(id)addDownloadingIconForIdentifier:(id)identifier;
-(void)removeApplicationIconForDownloadingIcon:(id)downloadingIcon;
-(id)addBookmarkIconForWebClip:(id)webClip;
-(void)addIconForApplication:(id)application;
-(void)loadAllIcons;
-(id)visibleIconIdentifiers;
-(id)leafIcons;
-(id)applicationIcons;
-(id)leafIconForIdentifier:(id)identifier;
-(id)applicationIconForDisplayIdentifier:(id)displayIdentifier;
-(id)iconState;
-(id)iconStatePath;
-(id)_iconState;
-(void)noteIconStateChangedExternally;
-(void)createIconLists;
-(void)uninstallBookmarkIcon:(id)icon;
-(void)addIcon:(id)icon;
-(void)removeIcon:(id)icon;
-(void)removeIconForIdentifier:(id)identifier;
-(id)indexPathForIconInPlatformState:(id)platformState;
-(id)_indexPathForIdentifier:(id)identifier inListRepresentation:(id)listRepresentation;
-(id)_indexPathForIdentifier:(id)identifier inListsRepresentation:(id)listsRepresentation;
-(BOOL)hasCachedUserGeneratedIconState;
-(void)clearCachedUserGeneratedIconState;
-(id)designatedIndexPathForNewIcon:(id)newIcon replaceExistingIcon:(BOOL*)icon;
-(void)_addNewIconToDesignatedLocation:(id)designatedLocation;
-(void)deleteIconState;
-(void)_writeIconStateWithNotification:(BOOL)notification;
-(void)saveIconState;
-(void)_replaceAppIconsWithDownloadingIcons;
-(void)_replaceAppIconWithDownloadingIcon:(id)downloadingIcon;
-(void)noteFolderStoppedAnimating;
-(void)noteDownloadsEnded;
-(void)noteDownloadsCompletedForIconIDs:(id)iconIDs;
-(void)removeDownloadedIconID:(id)anId;
-(id)downloadedIconIDs;
-(void)relayout;
-(void)uninstallApplicationIcon:(id)icon;
-(id)exportState:(BOOL)state;
-(id)_iTunesIconListsForLists:(id)lists preApex:(BOOL)apex;
-(id)_iTunesIconListForList:(id)list preApex:(BOOL)apex;
-(id)_iTunesIconCellForCell:(id)cell preApex:(BOOL)apex;
-(id)_iTunesDictionaryForLeafIcon:(id)leafIcon;
-(BOOL)importState:(id)state;
@end

