/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSIndexPath;

@interface SBIconIndexPath : NSObject {
	NSIndexPath* _listIndexes;
	NSIndexPath* _iconIndexes;
}
@property(retain, nonatomic) NSIndexPath* listIndexes;
@property(retain, nonatomic) NSIndexPath* iconIndexes;
+(id)indexPathWithIconIndex:(unsigned)iconIndex;
+(id)indexPathWithIconIndex:(unsigned)iconIndex listIndex:(unsigned)index;
-(void)dealloc;
-(void)pushListIndex:(unsigned)index;
-(void)pushIconIndex:(unsigned)index;
-(unsigned)popListIndex;
-(unsigned)popIconIndex;
-(unsigned)outermostListIndex;
-(unsigned)outermostIconIndex;
-(id)indexPathByPoppingOutermostListAndIconIndexes;
-(id)indexPathByPushingOutermostListIndex:(unsigned)index iconIndex:(unsigned)index2;
-(BOOL)isEmpty;
@end

