/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "SpringBoard-Structs.h"

@class SBIcon;

@interface SBIconRotationContainer : UIView {
	UIView* _startSnapshot;
	UIView* _endSnapshot;
	SBIcon* _icon;
	BOOL _shouldCrossfade;
}
@property(retain, nonatomic) SBIcon* icon;
-(void)dealloc;
-(void)setStartIcon:(id)icon endIcon:(id)icon2;
-(void)setOrigin:(CGPoint)origin;
-(void)prepareToCrossfade;
-(void)crossfadeWithDuration:(double)duration;
-(id)newSnapshot:(id)snapshot includingShadows:(BOOL)shadows;
@end

