/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"


@interface SBLowPowerAlertItem : SBAlertItem {
	unsigned _talkLevel;
}
+(id)systemVersionDescription;
+(void)saveLowBatteryLogWithCapacity:(int)capacity voltage:(int)voltage;
+(unsigned)_thresholdForLevel:(unsigned)level;
+(BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned)batteryLevel;
+(void)setBatteryLevel:(unsigned)level;
-(id)initWithLevel:(unsigned)level;
-(void)willPresentAlertView:(id)view;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)shouldShowInLockScreen;
-(BOOL)shouldShowInEmergencyCall;
-(BOOL)undimsScreen;
@end

