/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"


@interface SBLockScreenAudioRoutesAlertItem : SBAlertItem {
}
-(Class)alertSheetClass;
-(id)alertSheet;
-(BOOL)allowMenuButtonDismissal;
-(void)willRelockForButtonPress:(BOOL)buttonPress;
-(BOOL)shouldShowInLockScreen;
-(BOOL)togglesMediaControls;
-(BOOL)allowAutoUnlock;
-(void)performUnlockAction;
-(void)audioRoutingPicker:(id)picker didSelectRouteAtIndex:(int)index;
@end

