/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>

@class SBApplication, UIWindow, UIView;

@interface SBMiniAlertController : NSObject {
	SBApplication* _displayShowingAnAlert;
	UIWindow* _dimmingWindow;
	unsigned _miniAlertVisible : 1;
	unsigned _showDimmingWindowAfterAlertsDismissed : 1;
	UIView* _hiddenAlertWindow;
	CGAffineTransform _dimmingWindowTransform;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(id)dimImageForKeyboard:(BOOL)keyboard;
-(void)showDimmingWindow;
-(void)finishedAnimatingDimWindowOut:(id)anOut didFinish:(id)finish;
-(void)cancelHideDimmingWindow;
-(void)hideDimmingWindowAfterDelay;
-(void)hideDimmingWindow;
-(void)applyTransformToDimmingWindow:(CGAffineTransform)dimmingWindow;
-(void)deactivateAlertItemsForDisplay:(id)display;
-(void)displayWillShowMiniAlert:(id)display fenceId:(unsigned)anId;
-(id)displayShowingAnAlert;
-(void)displayWillDismissMiniAlert:(id)display andShowAnother:(BOOL)another fenceId:(unsigned)anId;
-(void)displayDidDismissMiniAlert:(id)display;
-(void)showApplicationMiniAlertsIfNeeded;
-(void)hideApplicationMiniAlerts;
-(void)noteMiniAlertStateChanged;
-(void)hideAlertWindowForFullscreenAlertActivation:(id)fullscreenAlertActivation;
-(void)noteFullscreenAlertsDismissed;
-(BOOL)miniAlertVisible;
-(BOOL)canShowAlerts;
@end

