/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIAlertView.h>

@class UIButton, UILabel, UISlider;

@interface SBNowPlayingAlertSheet : UIAlertView {
	CGRect normalSliderFrame;
	CGRect narrowSliderFrame;
	BOOL showingSliderOrLabel;
	UIButton* routeButton;
	UISlider* volumeSlider;
	UILabel* routeLabel;
}
@property(assign, nonatomic) CGRect normalSliderFrame;
@property(assign, nonatomic) CGRect narrowSliderFrame;
@property(retain, nonatomic) UISlider* volumeSlider;
@property(retain, nonatomic) UIButton* routeButton;
@property(retain, nonatomic) UILabel* routeLabel;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_positionControlButton:(int)button withFloor:(float)floor;
-(void)showRouteButton:(BOOL)button volumeSlider:(BOOL)slider animated:(BOOL)animated;
-(void)layout;
@end

