/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface SBOrientationLockManager : NSObject {
	int _override;
	int _lockedOrientation;
	int _overrideOrientation;
}
+(id)sharedInstance;
-(void)restoreStateFromPrefs;
-(void)dealloc;
-(void)lock;
-(void)lock:(int)lock;
-(void)unlock;
-(BOOL)isLocked;
-(int)lockOrientation;
-(void)setLockOverride:(int)override orientation:(int)orientation;
-(int)lockOverride;
-(void)updateLockOverrideForCurrentDeviceOrientation;
-(void)_changeLockState:(id)state;
-(BOOL)_effectivelyLocked;
-(int)_effectiveOrientation;
-(int)_deviceOrientationFromInterfaceOrientation:(int)interfaceOrientation;
@end

