/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString;

@interface SBPlatformController : NSObject {
	NSString* _currentConfigurationName;
	NSMutableDictionary* _currentConfiguration;
	NSMutableDictionary* _currentCapabilities;
	NSDictionary* _discoveredCapabilities;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(id)systemBuildVersion;
-(id)infoForCapability:(id)capability;
-(void)setValue:(id)value forCapability:(id)capability;
-(void)addCapabilities:(id)capabilities resetCapabilites:(id)capabilites;
-(BOOL)hasCapability:(id)capability;
-(id)enabledCapabilities;
-(BOOL)hasRestriction:(id)restriction;
-(BOOL)canDisplayHomescreenWallpaper;
-(id)platformName;
-(id)iconState;
-(void)_addIconListIdentifiers:(id)identifiers toSet:(id)set;
-(id)defaultDisplayIdentifiers;
-(BOOL)matchesPlatforms:(id)platforms;
-(id)localizedPlatformName;
-(BOOL)isInternalInstall;
-(BOOL)isCarrierInstall;
-(void)noteITunesStoreCapabilityChanged;
-(id)currentConfigurationName;
-(void)postCurrentConfiguration;
-(void)_mergeDictionary:(id)dictionary intoDictionary:(id)dictionary2;
-(void)_addConfigurationNamed:(id)named toCompositeDictionary:(id)compositeDictionary;
-(BOOL)allowSensitiveUI:(BOOL)ui hasInternalBundle:(BOOL)bundle;
-(BOOL)isCarrierInstall:(BOOL)install hasInternalBundle:(BOOL)bundle;
-(BOOL)allowYouTube;
-(BOOL)allowYouTubePlugin;
-(void)discoverCurrentConfiguration;
-(CFBooleanRef)currentITunesStoreCapability;
-(void)noteConfigurationChangedWithKeys:(id)keys;
@end

