/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertDisplay.h"

@class SBPowerDownController, NSTimer, TPBottomButtonBar, TPTopLockBar;

@interface SBPowerDownView : SBAlertDisplay {
	UIView* _dimView;
	TPTopLockBar* _lockView;
	TPBottomButtonBar* _cancelView;
	SBPowerDownController* _powerDownController;
	NSTimer* _autoDismissTimer;
}
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)cancelAutoDismissTimer;
-(void)resetAutoDismissTimer;
-(void)cancel:(id)cancel;
-(void)lockBarUnlocked:(id)unlocked;
-(void)lockBarStartedTracking:(id)tracking;
-(void)lockBarStoppedTracking:(id)tracking;
-(void)powerDown:(id)down;
-(void)setPowerDownController:(id)controller;
-(void)finishedAnimatingIn;
-(void)finishedAnimatingOut;
-(void)notifyDelegateOfPowerDown;
-(void)animateIn;
-(void)animateOut;
-(void)animateDark;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
@end

