/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert {
	int _count;
	id _delegate;
	SBPowerDownView* _powerDownView;
	BOOL _isFront;
}
+(id)sharedInstance;
-(void)dealloc;
-(double)autoLockTime;
-(BOOL)isOrderedFront;
-(void)orderFront;
-(void)orderOut;
-(id)powerDownViewWithSize:(CGSize)size;
-(void)activate;
-(void)_restoreIconListIfNecessary;
-(void)deactivate;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)alertDisplayWillBecomeVisible;
-(void)setDelegate:(id)delegate;
-(void)powerDown;
-(void)cancel;
@end

