/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "SBRemoteLocalNotificationAlertDelegate.h"
#import "APSConnectionDelegate.h"

@class NSMutableDictionary, NSString;

@interface SBRemoteNotificationServer : NSObject <APSConnectionDelegate, SBRemoteLocalNotificationAlertDelegate> {
	NSMutableDictionary* _bundleIdentifiersToClients;
	NSMutableDictionary* _environmentsToConnections;
	NSString* _lastNotificationReceivedBundleIdentifier;
}
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)run;
-(void)remoteLocalNotificationAlertShouldLaunch:(id)remoteLocalNotificationAlert forApplication:(id)application;
-(void)connection:(id)connection didReceivePublicToken:(id)token;
-(void)noteApplicationFinishedLaunching:(id)launching;
-(void)connection:(id)connection didReceiveMessageForTopic:(id)topic userInfo:(id)info;
-(id)lastNotificationReceivedBundleIdentifier;
-(id)allAppEnabledTypeValues;
-(id)allSettingsEnabledTypeValues;
-(void)calculateTopics;
-(void)registerApplication:(id)application forEnvironment:(id)environment withTypes:(int)types;
-(void)unregisterApplication:(id)application;
-(int)getEffectiveEnabledTypesForApplication:(id)application;
-(BOOL)isSystemwideEnabled;
-(void)setSystemwideEnabled:(BOOL)enabled;
-(BOOL)hasRegisteredBundleIdentifiers;
-(void)setSettingsTypes:(int)types forBundleIdentifier:(id)bundleIdentifier;
-(id)getMessageUserInfoForBundleIdentifier:(id)bundleIdentifier;
@end

