/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"


@interface SBRestoreFailureAlertItem : SBAlertItem {
	BOOL _runningModal;
}
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)didPresentAlertView:(id)view;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(double)autoDismissInterval;
-(void)_rebootNow;
-(void)restartSystemEvent;
-(void)performUnlockAction;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)allowMenuButtonDismissal;
-(BOOL)shouldShowInLockScreen;
@end

