/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolder.h"

@class SBDockIconListModel;

@interface SBRootFolder : SBFolder {
	SBDockIconListModel* _dock;
}
+(int)maxListCount;
-(Class)listModelClass;
-(Class)listViewClass;
-(id)init;
-(void)dealloc;
-(id)dockModel;
-(id)listAtIndex:(unsigned)index;
-(unsigned)indexOfIconList:(id)iconList;
-(id)listContainingIcon:(id)icon;
-(id)listContainingLeafIconWithIdentifier:(id)identifier;
-(void)removeEmptyList:(id)list;
-(BOOL)isIconStateDirty;
-(void)markIconStateClean;
-(id)iconsOfClass:(Class)aClass;
-(id)indexPathForEntity:(id)entity;
-(BOOL)resetWithRepresentation:(id)representation leafIdentifiersAdded:(id*)added;
-(id)representation;
-(void)placeIconsOnFirstPage:(id)page;
@end

