/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchController.h"


@interface SBSearchControllerWildcat : SBSearchController {
	void* _addressBook;
}
-(void)dealloc;
-(void)controllerWasDeactivated;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)_populateCell:(id)cell withSearchResult:(id)searchResult;
-(id)_auxiliaryTitleForABRecordID:(int)abrecordID;
@end

