/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UITableViewCell.h>

@class UIFont, NSString, NSArray;

@interface SBSearchTableViewCell : UITableViewCell {
	UIFont* _titleFont;
	UIFont* _subtitleFont;
	NSString* _title;
	NSString* _subtitle;
	NSArray* _subtitleComponents;
	NSString* _auxiliaryTitle;
	NSString* _auxiliarySubtitle;
	BOOL _badged;
	BOOL _usesAlternateBackgroundColor;
	BOOL _isTopHit;
	BOOL _isBelowTopHit;
	BOOL _isFirstInTableView;
	BOOL _isFirstInSection;
	float _sectionHeaderWidth;
	float _edgeInset;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) NSArray* subtitleComponents;
@property(retain, nonatomic) NSString* auxiliaryTitle;
@property(retain, nonatomic) NSString* auxiliarySubtitle;
@property(assign, nonatomic, getter=isBadged) BOOL badged;
@property(assign, nonatomic) BOOL usesAlternateBackgroundColor;
@property(assign, nonatomic, getter=isTopHit) BOOL topHit;
@property(assign, nonatomic, getter=isBelowTopHit) BOOL belowTopHit;
@property(assign, nonatomic, getter=isFirstInTableView) BOOL firstInTableView;
@property(assign, nonatomic, getter=isFirstInSection) BOOL firstInSection;
@property(assign, nonatomic) float sectionHeaderWidth;
@property(assign, nonatomic) float edgeInset;
+(id)backgroundColor;
+(id)alternateBackgroundColor;
+(id)lineColor;
+(id)alternateLineColor;
+(id)topLineShadowColor;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)clearContents;
-(BOOL)_drawsContent;
-(void)_drawContentInRect:(CGRect)rect selected:(BOOL)selected;
-(void)drawRect:(CGRect)rect;
-(id)_scriptingInfo;
@end

