/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"


@interface SBSIMLockAlertItem : SBAlertItem {
	int _status;
	int _okButtonIndex;
	int _unlockButtonIndex;
}
+(id)alertTitleForStatus:(int)status languageCode:(id)code;
+(id)alertTitleForStatus:(int)status;
-(id)initWithStatus:(int)status;
-(void)dealloc;
-(BOOL)canUnlock;
-(id)alertTitleForLanguageCode:(id)languageCode;
-(id)alertTextForLanguageCode:(id)languageCode;
-(int)status;
-(void)didDeactivateForReason:(int)reason;
-(void)unlock;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
@end

