/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSIMToolkitTextAlertDisplay.h"


@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay {
}
+(id)newTopBarForInstance:(id)instance;
+(id)newBottomBarForInstance:(id)instance;
-(void)dismiss:(id)dismiss;
-(id)_activeCalls;
-(void)dial:(id)dial;
-(id)alertText;
@end

