/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface SBSMSManager : NSObject {
}
+(id)sharedSMSManager;
-(void)messageSent:(id)sent;
-(void)messageSendError:(id)error;
-(void)messageReceived:(id)received;
-(id)init;
-(void)dealloc;
-(id)badgeNumberOrString;
-(void)setBadgeNumberOrString:(id)string;
-(BOOL)isShowingSendFailure;
-(void)markMessageAsRead:(id)read;
-(void)updateSMSBadges;
@end

