/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"

@class NSString, CKMessage;

@interface SBSMSAlertItem : SBAlertItem {
	CKMessage* _message;
	int _alignment;
	BOOL _alignmentHasBeenSet;
	BOOL _displayingEntireMessage;
	BOOL _playedSound;
	NSString* _name;
}
+(BOOL)shouldPlayMessageReceived;
+(void)playMessageReceived;
+(void)prefsChanged;
+(BOOL)_showSMSPreview;
+(BOOL)shouldHideSMSPreview;
-(void)dealloc;
-(void)_tag;
-(void)_untag;
-(void)_deactivateAllTaggedSMSAlertItems;
-(void)willActivate;
-(void)didDeactivateForReason:(int)reason;
-(void)setMessage:(id)message;
-(void)willPresentAlertView:(id)view;
-(id)address;
-(id)name;
-(BOOL)senderIsVoicemail;
-(BOOL)hasAttachments;
-(id)messageText;
-(id)alertImageData;
-(int)_groupID;
-(void)reply;
-(Class)alertSheetClass;
-(id)alertSheet;
-(void)_markReadIfDisplayingEntireMessage;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(int)bodyTextAlignmentForAlertSheet:(id)alertSheet displayedLineCount:(int)count;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)lockLabel;
-(BOOL)willShowInAwayItems;
-(BOOL)shouldShowInEmergencyCall;
-(int)alertItemNotificationType;
-(id)alertItemNotificationDate;
-(id)alertItemNotificationSender;
@end

