/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "RadiosPreferencesDelegate.h"

@class NSDateFormatter, NSString, NSTimer, RadiosPreferences;

@interface SBStatusBarDataManager : NSObject <RadiosPreferencesDelegate> {
	struct {
		BOOL itemIsEnabled[20];
		BOOL timeString[64];
		int gsmSignalStrengthRaw;
		int gsmSignalStrengthBars;
		BOOL serviceString[100];
		BOOL serviceImageBlack[100];
		BOOL serviceImageSilver[100];
		BOOL operatorDirectory[1024];
		unsigned serviceContentType;
		int wifiSignalStrengthRaw;
		int wifiSignalStrengthBars;
		unsigned dataNetworkType;
		int batteryCapacity;
		unsigned batteryState;
		int bluetoothBatteryCapacity;
		int thermalColor;
		unsigned slowActivity : 1;
		BOOL activityDisplayId[256];
		unsigned bluetoothConnected : 1;
		unsigned displayRawGSMSignal : 1;
		unsigned displayRawWifiSignal : 1;
	} _data;
	int _actions;
	BOOL _itemIsEnabled[20];
	BOOL _itemIsCloaked[20];
	int _updateBlockDepth;
	BOOL _dataChangedSinceLastPost;
	NSDateFormatter* _timeItemDateFormatter;
	NSTimer* _timeItemTimer;
	NSString* _timeItemTimeString;
	RadiosPreferences* _radiosPrefs;
	BOOL _cellRadio;
	BOOL _registered;
	BOOL _simError;
	BOOL _simulateInCallStatusBar;
	NSString* _serviceString;
	NSString* _serviceImageBlack;
	NSString* _serviceImageSilver;
	NSString* _operatorDirectory;
	BOOL _showsActivityIndicatorOnHomeScreen;
	int _thermalColor;
}
+(id)sharedDataManager;
-(id)init;
-(void)dealloc;
-(void)beginUpdateBlock;
-(void)endUpdateBlock;
-(void)setStatusBarItem:(int)item enabled:(BOOL)enabled;
-(void)setStatusBarItem:(int)item cloaked:(BOOL)cloaked;
-(void)updateStatusBarItem:(int)item;
-(void)sendStatusBarActions:(int)actions;
-(void)enableLock:(BOOL)lock time:(BOOL)time;
-(void)setShowsActivityIndicatorOnHomeScreen:(BOOL)screen;
-(void)setTelephonyAndBluetoothItemsCloaked:(BOOL)cloaked;
-(void)setAllItemsExceptBatteryCloaked:(BOOL)cloaked;
-(void)setThermalColor:(int)color;
-(void)_initializeData;
-(void)_dataChanged;
-(void)_postData;
-(void)_updateTimeString;
-(void)_updateTimeItem;
-(void)_updateAirplaneMode;
-(void)_updateSignalStrengthItem;
-(void)_updateServiceItem;
-(void)_updateDataNetworkItem;
-(void)_updateBatteryItem;
-(void)_updateBatteryPercentItem;
-(void)_updateBluetoothItem;
-(void)_updateBluetoothBatteryItem;
-(void)_updateTTYItem;
-(void)_updateVPNItem;
-(void)_updateCallForwardingItem;
-(void)_updateActivityItem;
-(void)_updatePlayItem;
-(void)_updateLocationItem;
-(void)_updateRotationLockItem;
-(void)_updateThermalColorItem;
-(void)_registerForNotifications;
-(void)_unregisterForNotifications;
-(void)_significantTimeOrLocaleChange;
-(void)_didWakeFromSleep;
-(void)_batteryStatusChange;
-(void)_operatorChange;
-(void)_signalStrengthChange;
-(void)_ttyChange;
-(void)_callForwardingChange;
-(void)_vpnChange;
-(void)_dataNetworkChange;
-(void)airplaneModeChanged;
-(void)_bluetoothChange;
-(void)_bluetoothBatteryChange;
-(void)_locationStatusChange;
-(void)_rotationLockChange;
-(void)_configureTimeItemDateFormatter;
-(void)_stopTimeItemTimer;
-(void)_restartTimeItemTimer;
-(void)_updateTelephonyState;
-(void)toggleSimulatesInCallStatusBar;
-(id)_displayStringForSIMStatus:(id)simstatus;
-(id)_displayStringForRegistrationStatus:(int)registrationStatus;
-(void)_getBlackImageName:(id*)name silverImageName:(id*)name2 directory:(id*)directory forFakeCarrier:(id)fakeCarrier;
-(BOOL)_getBlackImageName:(id*)name silverImageName:(id*)name2 directory:(id*)directory forOperator:(id)anOperator statusBarCarrierName:(id*)name5;
@end

