/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSTimer;

@interface SBSyncController : NSObject {
	int _syncState;
	int _restoreState;
	int _resetState;
	int _sofwareUpdateState;
	int _restoreTimerState;
	NSTimer* _restoreTimer;
	BOOL _showingResetUI;
	BOOL _appsChangedDuringSync;
}
+(id)sharedInstance;
-(void)dealloc;
-(void)startObserving;
-(void)stopObserving;
-(BOOL)isSyncing;
-(int)syncState;
-(void)didEndSyncing;
-(void)suspendSyncing;
-(void)resumeSyncing;
-(void)cancelSyncing;
-(void)_notifyAppsSyncWillBegin;
-(void)didShowSyncPanel;
-(void)frontLockedWhenPossible;
-(void)beginSyncing;
-(void)iTunesSyncRequestedStart;
-(void)iTunesSyncPhaseDidFinish:(int)iTunesSyncPhase reason:(int)reason;
-(BOOL)isRestoring;
-(int)restoreState;
-(void)_notifyRestoreCanProceed;
-(void)_killApplications;
-(void)beginRestoring;
-(void)finishedTerminatingApplications;
-(void)cancelRestoring;
-(void)_rebootNow;
-(void)finishEndRestoring;
-(void)didEndRestoring:(int)restoring;
-(BOOL)isResetting;
-(int)resetState;
-(void)_delayedQuitApplications;
-(void)_delayedBeginReset;
-(void)beginResetting:(BOOL)resetting;
-(void)didEndResetting;
-(void)_resetStarted:(id)started;
-(void)_resetEnded:(id)ended;
-(void)_invalidateRestoreTimer;
-(BOOL)_isBackupAgentRunning;
-(void)_restoreTimerFired:(id)fired;
-(void)_setupRestoreTimer;
-(void)setSoftwareUpdateState:(int)state;
-(void)showPreSoftwareUpdateScreen;
-(BOOL)isSoftwareUpdating;
-(void)_appInstallationNotification;
-(BOOL)isInUse;
@end

