/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBSlidingAlertDisplay.h"


@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay {
}
+(id)newTopBarForInstance:(id)instance;
+(id)newBottomBarForInstance:(id)instance;
-(id)initWithSize:(CGSize)size;
-(void)_makeCall;
-(void)_chooseVoiceMode:(id)mode;
-(void)_chooseTTYMode:(id)mode;
-(void)_ignore:(id)ignore;
@end

