/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIWindowDelegate.h"
#import <Foundation/NSObject.h>

@class UIView, UIStatusBar, SBSlidingViewHighlight, UIControl, SBZoomView, UIWindow, SBWallpaperView, SBDismissOnlyAlertItem, SBAppSwitcherBarView, SBAppDosadoView, SBApplication;

@interface SBUIController : NSObject <UIWindowDelegate> {
	UIWindow* _window;
	UIView* _iconsView;
	UIView* _rootView;
	UIView* _contentView;
	SBWallpaperView* _wallpaperView;
	SBZoomView* _zoomLayer;
	UIStatusBar* _fakeSpringBoardStatusBar;
	UIView* _scatterFadeView;
	BOOL _showingScatterFadeView;
	SBAppSwitcherBarView* _switcherView;
	UIWindow* _blockingWindow;
	UIControl* _blockingView;
	SBApplication* _switcherHostedApp;
	SBSlidingViewHighlight* _highlightView;
	BOOL _stealingEvents;
	BOOL _lockedOrientation;
	BOOL _ignoringEvents;
	SBApplication* _toggleSwitcherAfterLaunchApp;
	SBAppDosadoView* _appToAppTransitionView;
	id _volumeHandler;
	BOOL _restoringIconList;
	BOOL _lastVolumeDownToControl;
	BOOL _shouldAutoLock;
	float _batteryCapacity;
	float _curvedBatteryCapacity;
	BOOL _isBatteryCharging;
	BOOL _isOnAC;
	BOOL _connectedToUnusableFirewire;
	BOOL _isConnectedToChargeIncapablePowerSource;
	int _batteryLoggingStartCapacity;
	SBDismissOnlyAlertItem* _fwChargingAlert;
}
+(int)displayedLevelForLockScreenBatteryLevel:(int)lockScreenBatteryLevel;
+(id)sharedInstance;
+(id)folderSwitcherLinenPath;
+(CFDataRef)_createDataWithMappedFile:(id)mappedFile;
+(id)folderSwitcherLinen;
-(void)_indicateConnectedToPower;
-(void)dealloc;
-(id)init;
-(void)animateAppleDown:(BOOL)down;
-(void)finishLaunching;
-(void)systemControllerRouteChanged:(id)changed;
-(void)lock:(BOOL)lock disableLockSound:(BOOL)sound;
-(void)lock:(BOOL)lock;
-(void)lock;
-(void)cleanUpAfterZoomAnimation;
-(void)cleanUpAfterSlideAnimation;
-(void)clearZoomLayer;
-(void)createFakeSpringBoardStatusBar;
-(void)clearFakeSpringBoardStatusBar;
-(void)setFakeSpringBoardStatusBarVisible:(BOOL)visible;
-(id)rootView;
-(id)contentView;
-(id)window;
-(void)setShouldRasterizeAndFreezeContentView:(BOOL)rasterizeAndFreezeContentView;
-(void)_updateWallpaperImage;
-(id)wallpaperView;
-(BOOL)isDisplayingWallpaper;
-(void)launchIcon:(id)icon;
-(void)activateApplicationAnimated:(id)animated;
-(void)activateApplicationFromSwitcher:(id)switcher;
-(void)releaseOrientationLockIfNecessary;
-(void)applicationHasDied:(id)died;
-(void)_setRoundedCornersOnZoomLayerIfNecessaryForApp:(id)app withCornersFrame:(CGRect)cornersFrame;
-(CGRect)statusBarStyle:(int)style hidden:(BOOL)hidden snapshotRectForOrientation:(int)orientation;
-(CGAffineTransform)_transformAndFrameForStatusBarWithOrientation:(int)orientation height:(float)height frame:(CGRect*)frame;
-(void)_showZoomLayerWithImage:(id)image;
-(void)showZoomLayerWithDefaultImageOfApp:(id)app includeStatusBar:(BOOL)bar;
-(id)_zoomViewForApplication:(id)application includeStatusBar:(BOOL)bar snapshotFrame:(CGRect*)frame;
-(id)_zoomViewForApplication:(id)application includeStatusBar:(BOOL)bar snapshotFrame:(CGRect*)frame canUseIOSurface:(BOOL)surface;
-(void)showZoomLayerWithIOSurfaceSnapshotOfApp:(id)app includeStatusBar:(BOOL)bar;
-(void)scatterIconListAndBar:(BOOL)bar;
-(void)scatterIconListAndBar:(BOOL)bar fade:(BOOL)fade animateWallpaper:(BOOL)wallpaper;
-(void)fadeIconsForScatter:(BOOL)scatter duration:(double)duration startTime:(double)time;
-(void)showScatterFadeView:(BOOL)view duration:(double)duration startTime:(double)time;
-(BOOL)isShowingScatterFadeView;
-(void)restoreIconListAnimated:(BOOL)animated;
-(void)restoreIconListAnimatedIfNeeded:(BOOL)needed animateWallpaper:(BOOL)wallpaper;
-(void)restoreIconListAnimated:(BOOL)animated animateWallpaper:(BOOL)wallpaper;
-(void)restoreIconListAnimated:(BOOL)animated animateWallpaper:(BOOL)wallpaper keepSwitcher:(BOOL)switcher;
-(void)animateApplicationActivation:(id)activation animateDefaultImage:(BOOL)image scatterIcons:(BOOL)icons;
-(void)animateApplicationActivationDidStop:(id)animateApplicationActivation finished:(id)finished context:(void*)context;
-(void)tearDownIconListAndBar;
-(void)animateApplicationSuspend:(id)suspend;
-(void)applicationSuspendSwitcherFadeDidStop:(id)applicationSuspendSwitcherFade;
-(void)applicationSuspendAnimationWillStart:(id)applicationSuspendAnimation context:(void*)context;
-(void)applicationSuspendAnimationDidStop:(id)applicationSuspendAnimation finished:(id)finished context:(void*)context;
-(id)_snapshotUIOfAppAndUnhost:(id)appAndUnhost;
-(void)_beginAppToAppTransition:(id)appTransition to:(id)to;
-(void)dosadoViewAnimationDidStop:(id)dosadoViewAnimation;
-(void)_clearAppToAppTransitionView;
-(void)animateApplicationSuspendFlip:(id)flip;
-(void)applicationSuspendFlipDidStop:(id)applicationSuspendFlip;
-(void)stopRestoringIconList;
-(void)zoomWallpaper:(BOOL)wallpaper startTime:(double)time duration:(double)duration;
-(void)finishedUnscattering;
-(BOOL)_handleButtonEventToSuspendDisplays:(BOOL)suspendDisplays displayWasSuspendedOut:(BOOL*)anOut;
-(BOOL)clickedMenuButton;
-(void)_displayDidLaunch:(id)_display;
-(void)_setToggleSwitcherAfterLaunchApp:(id)app;
-(void)_toggleSwitcher;
-(BOOL)handleMenuDoubleTap;
-(float)_appSwitcherRevealAnimationDelay;
-(void)_accessibilityWillBeginAppSwitcherRevealAnimation;
-(BOOL)activateSwitcher;
-(BOOL)_revealSwitcher:(double)switcher;
-(void)dismissSwitcher;
-(void)_dismissSwitcher:(double)switcher;
-(void)_unhostSwitcherAppImmediately:(BOOL)immediately;
-(BOOL)isSwitcherShowing;
-(void)_switcherBlockingViewHit:(id)hit;
-(void)_ignoreEvents;
-(void)_resumeEventsIfNecessary;
-(BOOL)_ignoringEvents;
-(void)wakeUp:(id)up;
-(void)handleVolumeEvent:(GSEventRef)event;
-(void)cancelVolumeEvent;
-(void)updateBatteryState:(id)state;
-(float)batteryCapacity;
-(int)batteryCapacityAsPercentage;
-(float)curvedBatteryCapacity;
-(int)curvedBatteryCapacityAsPercentage;
-(int)displayBatteryCapacityAsPercentage;
-(BOOL)isBatteryCharging;
-(BOOL)isOnAC;
-(BOOL)isConnectedToChargeIncapablePowerSource;
-(void)ACPowerChanged;
-(void)setIsConnectedToUnusableFirewireCharger:(BOOL)unusableFirewireCharger;
-(BOOL)isConnectedToUnusableFirewireCharger;
-(void)noteStatusBarHeightChanged:(id)changed;
-(id)_currentAppSurfaceImage:(id)image;
-(BOOL)shouldWindowUseOnePartInterfaceRotationAnimation:(id)animation;
-(BOOL)window:(id)window shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)rotatingContentViewForWindow:(id)window;
-(id)rotatingFooterViewForWindow:(id)window;
-(void)getRotationContentSettings:(XXStruct_3B_lsC*)settings forWindow:(id)window;
-(void)window:(id)window willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)window:(id)window willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)window:(id)window didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isHeadsetDocked;
-(BOOL)isHeadsetBatteryCharging;
-(unsigned char)headsetBatteryCapacity;
@end

