/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


@interface SBUserInstalledApplicationIcon : SBApplicationIcon {
}
-(BOOL)allowsUninstall;
-(void)completeUninstall;
-(BOOL)hasBeenSyncedBackToITunes;
-(id)ratingsAlertTitle;
-(id)ratingsAlertBody;
-(id)ratingsAlertSkipTitle;
-(id)ratingsAlertRateButtonTitle;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
@end

