/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"

@class NSString, NSDate;

@interface SBVoiceMailAlertItem : SBAlertItem {
	BOOL _isForVisualVoicemail;
	unsigned _recordUID;
	NSString* _title;
	NSString* _body;
	NSString* _rawSender;
	NSDate* _date;
}
@property(retain, nonatomic) NSDate* date;
@property(retain, nonatomic) NSString* rawSender;
-(void)dealloc;
-(BOOL)isForVisualVoicemail;
-(void)setIsVisualVoicemail:(BOOL)voicemail recordUID:(unsigned)uid;
-(BOOL)willShowInAwayItems;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)dismissOnLock;
-(id)lockLabel;
-(id)title;
-(void)setTitle:(id)title;
-(id)bodyText;
-(void)setBodyText:(id)text;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)_performAppropriateListenAction;
-(void)_launchPhoneAndDisplayVoicemailRecord:(int)record;
-(int)alertItemNotificationType;
-(id)alertItemNotificationDate;
-(id)alertItemNotificationSender;
@end

