/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import "SBAlertItem.h"

@class SBVODAlarm;

@interface SBVODAlertItem : SBAlertItem <UIAlertViewDelegate> {
	SBVODAlarm* _alarm;
}
+(id)activeAlertForAlarm:(id)alarm;
-(void)dealloc;
-(void)setAlarm:(id)alarm;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)unlocksScreen;
-(void)screenWillUndim;
-(void)willActivate;
-(void)willDeactivateForReason:(int)reason;
-(void)_updateText;
@end

