/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImageView.h>

@class UIImage;

@interface SBWallpaperView : UIImageView {
	int _orientation;
	UIImageView* _topGradient;
	UIImageView* _bottomGradient;
	BOOL _usesFilter;
	float _filterAlpha;
	float _gradientAlpha;
	CGRect _wallpaperContentsRect;
	UIImage* _uncomposedImage;
	UIImage* _portraitComposedImage;
	UIImage* _landscapeComposedImage;
}
@property(assign, nonatomic) int orientation;
@property(assign, nonatomic) float gradientAlpha;
+(void)initialize;
+(void)noteWallpaperPreferencesChanged;
+(int)_desktopVariant;
+(BOOL)lockScreenAndHomeScreenShareWallpaper;
-(id)initWithOrientation:(int)orientation;
-(void)dealloc;
-(void)_resetImage;
-(void)_setUsesComposedImage:(BOOL)image createGradientsIfNeeded:(BOOL)needed;
-(void)_wallpaperChanged;
-(void)_setOrientationAnimationFinished;
-(void)_setOrientation:(int)orientation duration:(double)duration force:(BOOL)force;
-(float)alpha;
-(void)setAlpha:(float)alpha;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(id)gradientImageForInterfaceOrientation:(int)interfaceOrientation;
-(CGRect)wallpaperContentsRect;
-(id)uncomposedImage;
-(void)replaceWallpaperWithImage:(id)image;
-(void)resetCurrentImageToWallpaper;
@end

