/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImageView.h>

@class SBWallpaperView, UIView;

@interface SBWallpaperClipView : UIImageView {
	SBWallpaperView* _wallpaperView;
	UIImageView* _gradientView;
	int _orientation;
	CGPoint _contentOffset;
	UIView* _maskView;
	BOOL _usesFilter;
}
@property(retain, nonatomic) SBWallpaperView* wallpaperView;
@property(assign, nonatomic) CGPoint contentOffset;
-(id)initWithFrame:(CGRect)frame wallpaperView:(id)view;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)setWallpaperView:(id)view force:(BOOL)force;
-(void)_setWallpaperAlpha:(float)alpha;
-(void)_wallpaperImageChanged:(id)changed;
-(void)_wallpaperFrameChanged:(id)changed;
-(void)_wallpaperAlphaChanged:(id)changed;
-(void)_gradientAlphaChanged:(id)changed;
-(void)_updateWallpaperImage;
-(void)_updateMask;
-(void)_recomputeGeometry;
-(void)setMaskView:(id)view;
@end

