/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"

@class UIWebClip;

@interface SBWidgetApplicationIcon : SBApplicationIcon {
	UIWebClip* _webClip;
}
-(id)initWithApplication:(id)application;
-(void)dealloc;
-(id)generateIconImage:(int)image;
-(BOOL)shouldEllipsizeLabel;
-(BOOL)allowsUninstall;
-(void)completeUninstall;
-(id)uninstallAlertTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertCancelTitle;
-(id)webClip;
-(id)folderTitleOptions;
-(id)folderFallbackTitle;
@end

