/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBWiFiPasswordAlertItem : SBAlertItem {
	id _delegate;
	NSString* _name;
}
@property(assign, nonatomic) id delegate;
-(id)initWithNetworkName:(id)networkName;
-(void)dealloc;
-(void)dismiss:(int)dismiss;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)returnKeyPressed:(id)pressed;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)dismissOnLock;
@end

