/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertItem.h"

@class NSDictionary, NSString, NSTimer, NSMutableArray, UITable;

@interface SBWiFiAlertItem : SBAlertItem {
	NSMutableArray* _networks;
	NSTimer* _scanTimer;
	UITable* _table;
	CGSize _size;
	int _joinRow;
	NSString* _password;
	NSDictionary* _joinDict;
	SBAlertItem* _childAlert;
	BOOL _selectingRow;
	BOOL _storedPassword;
	BOOL _passwordFailed;
	BOOL _sentResponse;
}
-(void)scan;
-(id)init;
-(int)_joinRow;
-(void)setNetworks:(id)networks;
-(void)_setDelegateForAlert:(id)alert delegate:(id)delegate;
-(void)_dismissCurrentChildAlert;
-(void)childAlertDismissed:(id)dismissed;
-(id)insertionsForNewNetworks:(id)newNetworks;
-(id)deletionSetForLostNetworks:(id)lostNetworks originalNetworks:(id)networks;
-(void)wifiManager:(id)manager scanCompleted:(id)completed;
-(void)_enableTable;
-(void)dismiss:(int)dismiss;
-(void)willDeactivateForReason:(int)reason;
-(void)willActivate;
-(void)wifiManager:(id)manager joinCompleted:(int)completed;
-(void)didPresentAlertView:(id)view;
-(void)passwordEntered:(id)entered;
-(void)dealloc;
-(void)_alertViewDismissed:(id)dismissed automatically:(BOOL)automatically;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)allowMenuButtonDismissal;
-(void)performUnlockAction;
-(int)numberOfRowsInTable:(id)table;
-(id)table:(id)table cellForRow:(int)row column:(id)column;
-(void)tableSelectionDidChange:(id)tableSelection;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(BOOL)dismissOnLock;
-(void)dismissAlertsForApplicationTransition;
-(void)didDeactivateForReason:(int)reason;
@end

